# Generated by Django 3.2.19 on 2023-06-01 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travellog', '0002_auto_20230530_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['-year']},
        ),
        migrations.RenameField(
            model_name='logentry',
            old_name='created_on',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='logentry',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='logentry',
            old_name='updated_on',
            new_name='last_updated',
        ),
        migrations.AddField(
            model_name='logentry',
            name='privacy',
            field=models.IntegerField(choices=[(0, 'Privat'), (1, 'Public')], default=0),
        ),
        migrations.AddField(
            model_name='logentry',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='logentry',
            name='country',
            field=models.ForeignKey(default='Planet Earth', on_delete=django.db.models.deletion.CASCADE, to='travellog.country'),
        ),
    ]
