# Generated by Django 3.2.19 on 2023-06-01 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travellog', '0004_alter_logentry_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='travellog.country'),
        ),
    ]
